### ISSUE TITLE
After logout I don't see real users in form

### ISSUE THREAD

**Issue by jimmbraddock** [FallingSnow/lightdm-webkit2-material2#1]
Hello. I can't choose my user on login form after logout. I see such users as gustav2, napoleonib, gorbachev, jackkennedy and etc, but not my. At first login is all ok.

**Comment by FallingSnow** [comment]
Sorry, must of missed the notification of this issue. Can you make sure you have the latest version of [`lightdm-webkit2-greeter`](https://github.com/Antergos/lightdm-webkit2-greeter).

**Comment by jimmbraddock** [comment]
Yes, I have latest version.
```bash
> sudo pacman -Qi lightdm-webkit2-greeter
Name            : lightdm-webkit2-greeter
Version         : 2.2.1-1
Description     : A webkit2 greeter for LightDM
Architecture    : x86_64
URL             : https://github.com/antergos/lightdm-webkit2-greeter
Licenses        : GPL3
Groups          : system
Provides        : lightdm-webkit2-greeter  lightdm-webkit-greeter
Depends On      : lightdm  webkit2gtk>=2.12  antergos-wallpapers  accountsservice
Optional Deps   : None
Required By     : lightdm-webkit-theme-material-git  lightdm-webkit2-theme-material2
Optional For    : None
Conflicts With  : lightdm-webkit2-greeter  lightdm-webkit-theme-antergos
Replaces        : lightdm-webkit-theme-antergos
Installed Size  : 2.75 MiB
Packager        : Antergos Build Server <dev@antergos.com>
Build Date      : Mon 26 Dec 2016 03:03:50 PM MSK
Install Date    : Fri 13 Jan 2017 08:25:45 AM MSK
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature

```

**Comment by FallingSnow** [comment]
Can you describe how you are logging out?

The mock users are only inserted when lightdm is not initialized. This bug would suggest an issue upstream.

**Comment by jimmbraddock** [comment]
Looks like the trouble in way logout. If I logout with help ui menu (I use gnome3) then all work fine. But if I logout with help shortcut `cmd + L`, then the trouble is detected. At least if I am using the original material or default antegros greeter then works fine.


Attach logs with start lightdm and logout with `cmd + L` after.
[bug.txt](https://github.com/FallingSnow/lightdm-webkit2-material2/files/703832/bug.txt) - log with bug.
[material_v1.txt](https://github.com/FallingSnow/lightdm-webkit2-material2/files/703833/material_v1.txt) - log original material.

**Comment by FallingSnow** [comment]
@jimmbraddock are you still having this issue?

**Comment by jimmbraddock** [comment]
@FallingSnow, thank you. I installed the last git version and it works.
