### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Megingelos** [FallingSnow/lightdm-webkit2-material2#12]
Hello there! I have to thank you for an incredible work but there are some problems with the Spanish version. Here are a few fixes:

{"user":"Usuario","password":"Contraseña","session":"Sesiones","welcomeBack":"¡Bienvenido!","signIn":"Inicia sesión","signingIn":"Iniciando sesión","hibernate":"Hibernar","shutdown":"Apagar","restart":"Reiniciar","suspend":"Suspender","settings":"Configuración","backgroundColorScheme":"Esquema de Color de fondo","density":"Densidad","imageLocation":"Ubicación de la imagen","imageDirectory":"Directorio de la","language":"Idioma","backgroundEngine":"Motor de fondo","clockFormat":"Formato de reloj","timeZone":"Zona horaria","animation":"Animación","uiScaling":"Escala de la interfaz de Usuario - {scale} %","about":"Acerca de","back":"Atrás","foundABug":"¿Encontré un error, donde puedo reportarlo?","settingAProfileIcon":"Establecer un icono de perfil","seeForMoreInfo":"Ver {link} para obtener más información.","Hour":"Hora","done":"hecho","randomDefault":"Al azar (por defecto)","red":"Rojo","reds":"Rojos","orange":"Naranja","blue":"Azul","blues":"Azul","purples":"Morados","purple":"Púrpura","oranges":"Naranjas","green":"Verde","yellow":"Amarillo","brown":"Marrón","image":"Imagen","randomImage":"Imagen al azar","alignment":"Alineación","incorrectPassword":"Contraseña incorrecta","zodiacDensityError":"Densidad debe ser entre {min} y {max}"}

**Comment by Megingelos** [comment]
Here's a better (and readable) version:

{
	"user":"Usuario",
	"password":"Contraseña",
	"session":"Sesiones",
	"welcomeBack":"¡Bienvenido!",
	"signIn":"Inicia sesión",
	"signingIn":"Iniciando sesión",
	"hibernate":"Hibernar",
	"shutdown":"Apagar",
	"restart":"Reiniciar",
	"suspend":"Suspender",
	"settings":"Configuración",
	"backgroundColorScheme":"Esquema de Color de fondo",
	"density":"Densidad",
	"imageLocation":"Ubicación de la imagen",
	"imageDirectory":"Directorio de la",
	"language":"Idioma",
	"backgroundEngine":"Motor de fondo",
	"clockFormat":"Formato de reloj",
	"timeZone":"Zona horaria",
	"animation":"Animación",
	"uiScaling":"Escala de la interfaz de Usuario - {scale} %",
	"about":"Acerca de",
	"back":"Atrás",
	"foundABug":"¿Encontré un error, donde puedo reportarlo?",
	"settingAProfileIcon":"Establecer un icono de perfil",
	"seeForMoreInfo":"Ver {link} para obtener más información.",
	"Hour":"Hora",
	"done":"hecho",
	"randomDefault":"Al azar (por defecto)",
	"red":"Rojo",
	"reds":"Rojos",
	"orange":"Naranja",
	"blue":"Azul",
	"blues":"Azul",
	"purples":"Morados",
	"purple":"Púrpura",
	"oranges":"Naranjas",
	"green":"Verde",
	"yellow":"Amarillo",
	"brown":"Marrón",
	"image":"Imagen",
	"randomImage":"Imagen al azar",
	"alignment":"Alineación",
	"incorrectPassword":"Contraseña incorrecta",
	"zodiacDensityError":"Densidad debe ser entre {min} y {max}"
}

**Comment by FallingSnow** [comment]
Thank you, you may submit a pull request by pressing the pencil (edit) button on the top right of https://github.com/FallingSnow/lightdm-webkit2-material2/blob/master/src/i18n/es.json.

**Comment by FallingSnow** [comment]
#13
