### ISSUE TITLE
Some Ideas for Features

### ISSUE THREAD

**Issue by domsch1988** [FallingSnow/lightdm-webkit2-material2#18]
I really like this theme so far. It's working really great. Some things that i noticed and wanted to let you know:
- On Dual screen setups the second screen is blank. Maybe the Picture/Background can be replicated, or the full greeter can be spanned across the screens?
- The background images don't work with symlinks. I have my current wallpaper linked in several places to have a cohesive experience. Having the option to use my current wallpaper on the greater would be epic.
- Some kind of "config" file for colors? The defaults work really well, but i wish i could change the black header to something else, or the font colors for white background images. The same goes for the zodiac effect. I really like the effect, but the color choices aren't really to my taste. Going through the one big js file makes it really tough to change those.
- Having a Font option? I like the default, but sometimes i like some change. Not really important, just an idea.

Don't feel like i'm criticizing, i'm not. I am in aw of what this already is i'd just like to give my input on how to improve things a bit.

**Comment by FallingSnow** [comment]
Sorry I never got back to you on this.

> On Dual screen setups the second screen is blank. Maybe the Picture/Background can be replicated, or the full greeter can be spanned across the screens?

This is the responsibility of the greeter, not theme.

> The background images don't work with symlinks. I have my current wallpaper linked in several places to have a cohesive experience. Having the option to use my current wallpaper on the greater would be epic.

This is the responsibility of the greeter, not theme.

> Some kind of "config" file for colors? The defaults work really well, but i wish i could change the black header to something else, or the font colors for white background images. The same goes for the zodiac effect. I really like the effect, but the color choices aren't really to my taste.

This seems a little overkill personally. I might accept a pull request though.

> Going through the one big js file makes it really tough to change those.

Material2 is built with webpack, edit these files: https://github.com/FallingSnow/lightdm-webkit2-material2/tree/master/src/components and rebuild the large bundle.js file with `npm run build`.
https://github.com/FallingSnow/lightdm-webkit2-material2/blob/82a837044b72149e21118dbf2edee988a891af0f/package.json#L7-L9

> Having a Font option? I like the default, but sometimes i like some change. Not really important, just an idea.

Maybe with a pull request.

Thanks for sharing your ideas.
