### ISSUE TITLE
Install Fail

### ISSUE THREAD

**Issue by haylinmoore** [FallingSnow/lightdm-webkit2-material2#20]
I ran the command `pacaur -S lightdm-webkit2-theme-material2`

~ » pacaur -S lightdm-webkit2-theme-material2          herohamp@archbook
:: Package lightdm-webkit2-theme-material2 not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (2)                    Old Version  New Version

aur/lightdm-webkit2-greeter                       2.2.5-1                   
aur/lightdm-webkit2-theme-material2               0.0.5-1                   

Repo Packages (2)                    Old Version  New Version  Download Size

extra/meson                                       0.44.1-1          0.47 MiB
community/ninja                                   1.8.2-1           0.00 MiB

Repo Download Size:   0.47 MiB
Repo Installed Size:  3.16 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving package(s)...
:: lightdm-webkit2-theme-material2 build files are up-to-date -- skipping
:: lightdm-webkit2-greeter build files are up-to-date -- skipping
:: Checking lightdm-webkit2-greeter integrity...
==> Making package: lightdm-webkit2-greeter 2.2.5-1 (Thu Mar  8 21:30:25 EST 2018)
==> Retrieving sources...
  -> Found 2.2.5.zip
  -> Found archlinux-logo.svg
  -> Found archlinux-user.svg
==> Validating source files with md5sums...
    2.2.5.zip ... Passed
    archlinux-logo.svg ... Passed
    archlinux-user.svg ... Passed
:: Checking lightdm-webkit2-theme-material2 integrity...
==> Making package: lightdm-webkit2-theme-material2 0.0.5-1 (Thu Mar  8 21:30:25 EST 2018)
==> Retrieving sources...
  -> Found lightdm-webkit2-material2-0.0.5.tar.gz
==> Validating source files with sha512sums...
    lightdm-webkit2-material2-0.0.5.tar.gz ... Passed
:: Building lightdm-webkit2-greeter package(s)...
==> Making package: lightdm-webkit2-greeter 2.2.5-1 (Thu Mar  8 21:30:26 EST 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Package (2)      New Version  Net Change  Download Size

community/ninja  1.8.2-1        0.31 MiB               
extra/meson      0.44.1-1       2.85 MiB       0.47 MiB

Total Download Size:   0.47 MiB
Total Installed Size:  3.16 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'meson-0.44.1-1-any.pkg.tar.xz' from mirrors.advancedhosters.com : The requested URL returned error: 404
error: failed retrieving file 'meson-0.44.1-1-any.pkg.tar.xz' from mirror.wdc1.us.leaseweb.net : The requested URL returned error: 404
error: failed retrieving file 'meson-0.44.1-1-any.pkg.tar.xz' from arch.mirrors.pair.com : The requested URL returned error: 404
error: failed retrieving file 'meson-0.44.1-1-any.pkg.tar.xz' from mirror.wdc1.us.leaseweb.net : The requested URL returned error: 404
error: failed retrieving file 'meson-0.44.1-1-any.pkg.tar.xz' from mirror.vtti.vt.edu : The requested URL returned error: 404
error: failed retrieving file 'meson-0.44.1-1-any.pkg.tar.xz' from arch.mirror.constant.com : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
==> ERROR: 'pacman' failed to install missing dependencies.
:: Building lightdm-webkit2-theme-material2 package(s)...
==> Making package: lightdm-webkit2-theme-material2 0.0.5-1 (Thu Mar  8 21:30:27 EST 2018)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: lightdm-webkit2-greeter
==> ERROR: 'pacman' failed to install missing dependencies.
:: failed to build lightdm-webkit2-greeter package(s)
:: failed to build lightdm-webkit2-theme-material2 package(s)

**Comment by FallingSnow** [comment]
Error while installing `lightdm-webkit2-greeter`.
