### ISSUE TITLE
Worked for a while, then changed something, now fails

### ISSUE THREAD

**Issue by mike-lawrence** [FallingSnow/lightdm-webkit2-material2#23]
I had this working for a while, installed via yay, but I was fiddling with the settings and now it's not working; lightdm shows me the dialog to use the default or fallback theme.Any idea how I can go about reverting this theme's settings? I've tried uninstalling and installing again, but that doesn't seem to work. Here's the contents of `/var/log/lightdm/seat0-greeter.log`:

    file:///usr/share/lightdm-webkit/themes/material2/bundle.js:33:507711: CONSOLE DEBUG Loading Theme
    file:///usr/share/lightdm-webkit/themes/material2/bundle.js:68:279949: CONSOLE DEBUG Main loaded. [object Object]
    file:///usr/share/lightdm-webkit/themes/material2/bundle.js:68:257533: CONSOLE DEBUG App loaded. [object Object]
    file:///usr/share/lightdm-webkit/themes/material2/bundle.js:68:261940: CONSOLE DEBUG Background loaded. [object Object]
    file:///usr/share/lightdm-webkit/themes/material2/bundle.js:68:263069: CONSOLE DEBUG Updated background. New engine: image
    file:///usr/share/lightdm-webkit/themes/material2/bundle.js:68:263308: CONSOLE DEBUG Clock Locale set to: en
    file:///usr/share/lightdm-webkit/themes/material2/bundle.js:33:20444: CONSOLE DEBUG Image loaded. [object Object]
    file:///usr/share/lightdm-webkit/themes/material2/bundle.js:68:180875: CONSOLE ERROR Error: Module build failed: Error: /home/mike/.cache/yay/lightdm-webkit2-theme-material2
    -git/src/lightdm-webkit2-material2/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or di
    rectory

        at Promise.all.then.arr (/home/mike/.cache/yay/lightdm-webkit2-theme-material2-git/src/lightdm-webkit2-material2/node_modules/execa/index.js:231:11)
        at process._tickCallback (internal/process/next_tick.js:68:7)

    ** (lightdm-webkit2-greeter:7010): WARNING **: 23:04:53.554: [ERROR] :: A problem was detected with the current theme. Falling back to default theme...

    (lightdm-webkit2-greeter:7010): Gtk-CRITICAL **: 23:04:58.211: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by FallingSnow** [comment]
You need to clear the local storage of lightdm-webkit2. Try putting webkit2 in debug mode, restart it and right click anywhere and select inspect element. A new window should appear. Go to the storage tab and clear all the storages. That should reset the settings. If that doesn't work let me know. Monday, 27 August 2018, 07:39PM -07:00 from Mike Lawrence  notifications@github.com :

**Comment by mike-lawrence** [comment]
That did the trick, thanks!

**Comment by FallingSnow** [comment]
You got it!
