### ISSUE TITLE
Error Loading Theme

### ISSUE THREAD

**Issue by terroreek** [FallingSnow/lightdm-webkit2-material2#4]
Hi,

I get an error trying to load this theme.  I have debugging on and the error I am getting in seat0-greeter.log when loading this theme is;

file:///usr/share/lightdm-webkit/themes/material2/bundle.js:128:4035: CONSOLE ERROR Error: Cannot find module './be.json'.

I get this error on debian sid, on my arch box I have no issue but I am installing AUR.  Vs using the tar file.

**Comment by FallingSnow** [comment]
What language are you using on your Debian system?

**Comment by terroreek** [comment]
us english.

**Comment by terroreek** [comment]
Pardon my ignorance, but is there any build instructions, so I can update my install on my debian system??

**Comment by FallingSnow** [comment]
Sorry, I forgot you error was on your debian system. I'll upload a build for you to use till a release is made. I'll upload it later today, around 3 hours from now.

I'll add some build instructions to the wiki later too.

If you can't wait or are feeling adventurous, you can try to decifer the PKGBUILD on the aur.

**Comment by FallingSnow** [comment]
[lightdm-webkit2-material2-0.0.3-1.tar.gz](https://github.com/FallingSnow/lightdm-webkit2-material2/files/739740/lightdm-webkit2-material2-0.0.3-1.tar.gz)

**Comment by terroreek** [comment]
Works great, just a couple of things I noticed.  The users are not populated automatically not that big of a deal (only in debian sid).  I find if you try to modify the image background and put in the wrong path or image name its not found the theme tends to lock up (both Arch and Debian).  Again, not a show stopper.

Thank you for fixing it and thank you for putting together a beautiful theme!! Let me know if there is anything else I can do to help.

**Comment by FallingSnow** [comment]
> The users are not populated automatically not that big of a deal (only in debian sid).

I assume this is an upstream bug. Either the greeter or lightdm's issue, most likely the greeter.

> I find if you try to modify the image background and put in the wrong path or image name its not found the theme tends to lock up (both Arch and Debian).

This is a known issue with webkit2gtk. Nothing we can do to fix it un
