### ISSUE TITLE
1 core at 100% at all times

### ISSUE THREAD

**Issue by TheSinding** [FallingSnow/lightdm-webkit2-material2#6]
Hi, i have a problem with 1 core staying at 100% when i use your theme

**Lightdm version:** 1.20
**Distribution:** Arch / Antergos

Want some log or ?

**Comment by FallingSnow** [comment]
Are you sure it only happens when you are using lightdm-webkit2-material2?

**Comment by TheSinding** [comment]
Yeah, I just tested it, found that it's the "Zodiac" setting that does it..

**Comment by FallingSnow** [comment]
Can you be a little more specific on the Zodiac setting?

**Comment by TheSinding** [comment]
The Zodiac bagground setting, with Random colors set.

**Comment by FallingSnow** [comment]
The CPU being stuck at 100% persists one you are logged in and exit the greeter, or only while you are in the greeter?

**Comment by TheSinding** [comment]
It persists, after a login..

**Comment by FallingSnow** [comment]
I believe the maxed out CPU are two different issues.

First off, I tested this with the latest git and while I have high cpu usage in the greeter using zodiac (expected because no hw acceleration), the usage drops as soon as I login.

I believe the high CPU usage while you are logged in is attributed to something else. Can you please show a screen shot of htop sorted by CPU usage once you are logged in?

**Comment by TheSinding** [comment]
Hrm, for some reason, it works now.. 
I'll send you if it does it again .. 

But do you have an idea, on what the problem might be?

**Comment by TheSinding** [comment]
I think the greeter might have been running in the bagground, for some reason

**Comment by TheSinding** [comment]
It did it agian https://ptpb.pw/Boqa.png

**Comment by FallingSnow** [comment]
Hmm, your right, that is strange. Your using Zodiac as your background in the greeter correct?

**Comment by TheSinding** [comment]
Yup.. But now thinking about this.. I thinks its more of a lightdm problem, only local to my machine..
It does this after my laptop have been sleeping, then when i log in, it looks like the lightdm crashes, and recovers, then I have to log in again.

**Comment by FallingSnow** [comment]
Him, I can write kind of a hacky fix that would just pause Zodiac after a correct login is made. But your lightdm problem will still persist, just without the 100% cpu caused by Zodiac.

Let me know if that would be the easiest route for you.

**Comment by TheSinding** [comment]
I should fix my lightdm, there is actually nothing wrong with your code..
