### ISSUE TITLE
dm-tool lock bug

### ISSUE THREAD

**Issue by joksik** [FallingSnow/lightdm-webkit2-material2#9]
Hello. When my laptop goes into standby or i lock my screen with dm-tool lock I can`t  log in again. Lightdm looks like a demo on github - strange users on the list

**Comment by FallingSnow** [comment]
Is this related to issue #1?

**Comment by joksik** [comment]
yes i have the same problem as jimmbraddock. when my screen is lock or i lock manually with dm-tool lock lightdm looks like [DEMO ](https://fallingsnow.github.io/lightdm-webkit2-material2)

**Comment by FallingSnow** [comment]
Did you look at what the previous user did to resolve it?

**Comment by joksik** [comment]
I've temporarily fixed the problem by installing xscreensaver. Now when I do not use my computer for a long time, the screensaver starts up and I can log back in later. The problem only occurs by typing in the terminal: dm-tool lock but I can live with it ;)

**Comment by FallingSnow** [comment]
Yeah, I've tried to solve this issue before, but it seems to be especially tricky.

I'm happy you solved your issue.
